<?php


class adduserresult extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=4";
        $roleres=mysqli_query($rolelink,$rolequery,MYSQLI_STORE_RESULT);

        if (mysqli_num_rows($roleres)>0){
            $uname=trim(strip_tags($_POST['uname']));
            $checklink=mysqli_connect( HOST, USER, PASSWORD, DB );
            $checkquery="SELECT Id FROM autoriation WHERE UserName='$uname'";
            $checkres=mysqli_query($checklink,$checkquery,MYSQLI_STORE_RESULT);
            if (mysqli_num_rows($checkres)>0){
                echo 'Этот пользователь уже существует.';
            }
            else{
                $userlink=mysqli_connect( HOST, USER, PASSWORD, DB );
                $userquery="INSERT INTO autoriation (UserName,Password) VALUES('$uname','$uname')";
                $userres=mysqli_query($userlink,$userquery,MYSQLI_STORE_RESULT);
                $id=mysqli_insert_id($userlink);

                $userquery="INSERT INTO bank (UserId) VALUES ($id)";
                $userres=mysqli_query($userlink,$userquery,MYSQLI_STORE_RESULT);

                $userquery="INSERT INTO userroles (UserId,RoleId) VALUES ($id,1)";
                $userres=mysqli_query($userlink,$userquery,MYSQLI_STORE_RESULT);
                echo 'Пользователь успешно добавлен.';
            }
        }
        else{
            echo 'У вас нет доступа для просмотра этой страницы.';
        }
    }
}