<?php


class adduser extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=4";
        $roleres=mysqli_query($rolelink,$rolequery,MYSQLI_STORE_RESULT);

        if (mysqli_num_rows($roleres)>0){
            echo '<form method="post" action="?option=adduserresult">
                    <lable>Имя персонажа</lable><br>
                    <input type="text" name="uname"> <br>
                    <input type="submit" value="Добавить">  
                  </form>';
        }
        else{
            echo 'У вас нет доступа для просмотра этой страницы.';
        }
    }
}