<?php


class autorisation extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        if (!isset($_SESSION['UserId']))
        {
        echo '<form method="post" action="?option=autorisationres">
                <table>
                    <tr>
                        <td><label for="loginField">Логин</label></td>
                        <td><input id="loginField" type="text" name="login"></td>
                    </tr>
                    <tr>
                        <td><label for="passwordField">Пароль</label></td>
                        <td><input id="passwordField" type="password" name="password"></td>
                    </tr>
                    <tr>
                        <td><input type="submit"></td>
                    </tr>
                </table>
            </form>';
        }
        else
            {
            echo 'Вы уже авторизированы как '.$_SESSION['UserName'];
        }
    }
}