<?php

class autorisationres extends  core
{
    public  function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        $link=mysqli_connect( HOST, USER, PASSWORD, DB );
        $login=trim(strip_tags($_POST['login']));
        $password=trim(strip_tags($_POST['password']));
        $query="SELECT Id FROM autoriation WHERE UserName='$login' AND Password='$password'";
        $res=mysqli_query($link,$query,MYSQLI_STORE_RESULT);

        if(mysqli_num_rows($res)>0)
        {
            $user=mysqli_fetch_array($res,MYSQLI_ASSOC);
            $_SESSION['UserName']=$login;
            $_SESSION['UserId']=$user['Id'];
            $userid=$user['Id'];
            $query="SELECT RoleId FROM userroles WHERE UserId='$userid'";
            $res2=mysqli_query($link,$query,MYSQLI_STORE_RESULT);
            $role=mysqli_fetch_array($res2,MYSQLI_ASSOC);
            $_SESSION['role']=$role['RoleId'];
            echo 'Добро пожаловать, '.$_SESSION['UserName'];
        }
        else
        {
            echo 'Логин или пароль введены неправильно.';
        }
    }
}