<?php


class deleteuser extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub
        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery2="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=6";
        $roleres2=mysqli_query($rolelink,$rolequery2,MYSQLI_STORE_RESULT);

        if(mysqli_num_rows($roleres2)>0){
            $uid = $_POST['id'];
            $lootlink=mysqli_connect( HOST, USER, PASSWORD, DB );
            $lootquery = "DELETE FROM userloot WHERE UserId=$uid";
            $lootres=mysqli_query($lootlink,$lootquery,MYSQLI_STORE_RESULT);

        }
        else{
            echo 'Вы не можете просматривать эту страницу';
        }
    }
}