<?php


class deletrequest extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        $redlink = mysqli_connect(HOST, USER, PASSWORD, DB);
        $userrole = $_SESSION['role'];
        $redquery = "SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=7";
        $redres = mysqli_query($redlink, $redquery, MYSQLI_STORE_RESULT);

        if (mysqli_num_rows($redres) > 0) {
            $lootid=$_POST['id'];

            $link =  mysqli_connect(HOST, USER, PASSWORD, DB);
            $delquery = "DELETE FROM userloot WHERE LootId = $lootid";
            $delres = mysqli_query($link,$delquery,MYSQLI_STORE_RESULT);

            $delquery = "SELECT ChestId FROM loot WHERE Id=$lootid";
            $delres = mysqli_query($link,$delquery,MYSQLI_STORE_RESULT);
            $loot = mysqli_fetch_array($delres, MYSQLI_ASSOC);
            $chestid=$loot['ChestId'];

            $delquery ="DELETE FROM loot WHERE Id=$lootid";
            $delres = mysqli_query($link,$delquery,MYSQLI_STORE_RESULT);

            $managerName=$_SESSION['UserName'];
            $chestquery="SELECT LootName FROM lootchests WHERE Id=$chestid";
            $chestres=mysqli_query($link,$chestquery,MYSQLI_STORE_RESULT);
            $chest=mysqli_fetch_array($chestres,MYSQLI_ASSOC);
            $chestname = $chest['LootName'];

            $datetime=date('Y-m-j H:i:s');

            $logquery="INSERT INTO Logs (OperationId,ByName,Sum,AdresantName,DateTime) VALUES (4,'$managerName',0,'$chestname','$datetime')";
            $logres=mysqli_query($link,$logquery,MYSQLI_STORE_RESULT);

            echo 'Лот удален';
        }
        else {
            echo 'Вы не можете просматривать эту страницу';
        }
    }
}