<?php


class givecashresult extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub
        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=2";
        $roleres=mysqli_query($rolelink,$rolequery,MYSQLI_STORE_RESULT);

        if(mysqli_num_rows($roleres)>0){
            $uid=$_POST['uid'];
            $cash=$_POST['cash'];
            $cashlink=mysqli_connect( HOST, USER, PASSWORD, DB );
            $cashquery="UPDATE bank SET Sum=Sum-$cash WHERE UserId=$uid";
            $cachres=mysqli_query($cashlink,$cashquery,MYSQLI_STORE_RESULT);

            $userquery="SELECT UserName FROM autoriation WHERE UserId=$uid";
            $userres=mysqli_query($cashlink,$userquery,MYSQLI_STORE_RESULT);
            $user=mysqli_fetch_array($userres,MYSQLI_ASSOC);
            $uname=$user['UserName'];

            $datetime=date('Y-m-j H:i:s');
            $managerName=$_SESSION['UserName'];
            $logquery="INSERT INTO Logs (OperationId,ByName,Sum,AdresantName,DateTime) VALUES (1,'$managerName',$cash,'$uname','$datetime')";
            $logres=mysqli_query($cashlink,$logquery,MYSQLI_STORE_RESULT);
            echo 'Счет обновлен.';
        }
        else{
            echo 'У вас нет прав дл просмотра этой страницы.';
        }
    }
}