<?php


class givecashresult extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub
        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=2";
        $roleres=mysqli_query($rolelink,$rolequery,MYSQLI_STORE_RESULT);

        if(mysqli_num_rows($roleres)>0){
            $uid=$_POST['uid'];
            $cash=$_POST['cash'];
            $cashlink=mysqli_connect( HOST, USER, PASSWORD, DB );
            $cashquery="UPDATE bank SET Sum=Sum-$cash WHERE UserId=$uid";
            $cachres=mysqli_query($cashlink,$cashquery,MYSQLI_STORE_RESULT);


            $datetime=date('Y-m-j H:i:s');
            $managerId=$_SESSION['UserId'];
            $logquery="INSERT INTO Logs (OperationId,ById,Sum,AdresantId,DateTime) VALUES (1,$managerId,$cash,$uid,'$datetime')";
            $logres=mysqli_query($cashlink,$logquery,MYSQLI_STORE_RESULT);
            echo 'Счет обновлен.';
        }
        else{
            echo 'У вас нет прав дл просмотра этой страницы.';
        }
    }
}