<?php


class givecash extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub
        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=2";
        $roleres=mysqli_query($rolelink,$rolequery,MYSQLI_STORE_RESULT);

        if(mysqli_num_rows($roleres)>0){
            $userlink=mysqli_connect( HOST, USER, PASSWORD, DB );
            $userquery="SELECT Id,UserName FROM autoriation";
            $userres=mysqli_query($userlink,$userquery,MYSQLI_STORE_RESULT);
            echo '<table><tr><td>Ник</td><td>На счету</td><td>Выдать</td></tr>';

            for ($i=0;$i<mysqli_num_rows($userres);$i++){
                $user=mysqli_fetch_array($userres,MYSQLI_ASSOC);
                echo '<tr><td>'.$user['UserName'].'</td>';
                $rlink=mysqli_connect( HOST, USER, PASSWORD, DB );
                $uid=$user['Id'];
                $rquery="SELECT Sum FROM bank WHERE UserId=$uid";
                $rres=mysqli_query($rlink,$rquery,MYSQLI_STORE_RESULT);
                $role=mysqli_fetch_array($rres,MYSQLI_ASSOC);
                echo '<td>'.$role['Sum'].'</td><td>';

                echo '<form method="post" action="?option=givecashresult">
<input type="number" name="cash"> <br>
<input value="'.$uid.'" hidden="hidden" name="uid"><input type="submit" value="Изменить"></form>';
                echo '</td></tr>';
            }

            echo '</table>';
        }
        else{
            echo 'У вас нет доступа для просмотра этой страницы.';
        }
    }
}