<?php

class main extends core
{
    public function get_body()
    {
        $link=mysqli_connect( HOST, USER, PASSWORD, DB );
        parent::get_body(); // TODO: Change the autogenerated stub
        $query="SELECT UserId,Sum FROM `bank`";
        $res=mysqli_query( $link,$query,MYSQLI_USE_RESULT);
        echo '<table>';

        while ($cash=mysqli_fetch_array($res, MYSQLI_ASSOC))
        {
            $link2=mysqli_connect( HOST, USER, PASSWORD, DB );
            $UserId=$cash['UserId'];
            $ures=mysqli_query($link2,"SELECT * FROM `autoriation` WHERE Id=$UserId",MYSQLI_USE_RESULT);
            $user=mysqli_fetch_array($ures, MYSQLI_ASSOC);
            echo '<tr><td>'.$user['UserName'].'</td><td>'.$cash['Sum'].'</td></tr>';

        }

        mysqli_close($link2);
        echo '</table>';
        mysqli_close($link);
    }
}