<?php


class makerequest extends core
{   public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        if(!isset($_SESSION['UserId'])){
            echo 'Войдите, чтобы просматривать эту страницу: <a href="?option=autorisation">Войти</a>';
        }
        else
            {
                echo '<form method="post" action="?option=requestresult">';
                $link=mysqli_connect( HOST, USER, PASSWORD, DB );
                $query="SELECT * FROM lootchests";
                $chestres=mysqli_query($link,$query,MYSQLI_STORE_RESULT);
                echo '<select name="chest">';

                for ($i=0;$i<mysqli_num_rows($chestres);$i++){
                    $chest=mysqli_fetch_array($chestres,MYSQLI_ASSOC);
                    echo '<option value="'.$chest['Id'].'">'.$chest['LootName'].'</option>';
                }

                echo '</select><br><br>';

                $query="SELECT UserName, Id FROM autoriation";
                $userres=mysqli_query($link,$query,MYSQLI_STORE_RESULT);

                for($i=0; $i<mysqli_num_rows($userres);$i++){
                    $user=mysqli_fetch_array($userres);
                    echo '<input type="checkbox" name="user[]" value="'.$user['Id'].'">'.$user['UserName'].'<br>';
                }
                echo '<br><input type="submit"></form>';
        }
    }
}