<?php


class passwrenew extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        if (isset($_SESSION['UserId']))
        {
        echo '<form method="post" action="?option=passrenewres">
                <table>
                    <tr>
                        <td><label for="oldPass">Старый пароль</label></td>
                        <td><input id="oldPass" type="password" name="oPass"></td>
                    </tr>
                    <tr>
                        <td><label for="passwordField">Новый Пароль</label></td>
                        <td><input id="passwordField" type="password" name="password"></td>
                    </tr>
                    <tr>
                        <td><input type="submit"></td>
                    </tr>
                </table>
            </form>';
        }
        else
            {
            echo 'Войдите, чтобы просматривать эту страницу.';
        }
    }
}