<?php


class requestresult extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        if(!isset($_SESSION['UserId'])){
            echo 'Неверный адрес.';
        }
        else{
            $users = $_POST['user'];

            if(empty($users))
            {
                echo("Вы не выбрали ни одного пользователя.");
            }
            else
            {
            $creator=$_SESSION['UserId'];
            $chestId=$_POST['chest'];
            $datetime=date('Y-m-j H:i:s');
            $status=1;
            $link=mysqli_connect( HOST, USER, PASSWORD, DB );
            $query = "INSERT INTO loot (CreatedById,ChestId,EventDateTime,StatusId) VALUES ($creator,$chestId,'$datetime',$status)";
            $res=mysqli_query($link, $query, MYSQLI_STORE_RESULT);
            $id=mysqli_insert_id($link);
            $N = count($users);

            for($i=0; $i < $N; $i++)
            {
                $link2=mysqli_connect( HOST, USER, PASSWORD, DB );
                $query2="INSERT INTO userloot (UserId, LootId) VALUES  ($users[$i],$id)";
                $res=mysqli_query($link2,$query2,MYSQLI_STORE_RESULT);
            }
                echo 'Заявка отправлена.';
            }
        }
    }
}