<?php


class roleredresult extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=3";
        $roleres=mysqli_query($rolelink,$rolequery,MYSQLI_STORE_RESULT);

        if(mysqli_num_rows($roleres)>0){
            $roleid=$_POST['roles'];
            $uid=$_POST['uid'];
            $rlink=mysqli_connect( HOST, USER, PASSWORD, DB );
            $rquery="UPDATE userroles SET RoleId=$roleid WHERE UserId=$uid";
            $rres=mysqli_query($rlink,$rquery,MYSQLI_STORE_RESULT);
            echo 'Роль успешно изменена.';
        }
        else{
            echo 'У вас нет доступа для просмотра этой страницы.';
        }
    }
}