<?php


class rolered extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=3";
        $roleres=mysqli_query($rolelink,$rolequery,MYSQLI_STORE_RESULT);

        if(mysqli_num_rows($roleres)>0){
            $userlink=mysqli_connect( HOST, USER, PASSWORD, DB );
            $userquery="SELECT Id,UserName FROM autoriation";
            $userres=mysqli_query($userlink,$userquery,MYSQLI_STORE_RESULT);
            echo '<table><tr><td>Ник</td><td>Роль</td><td>Изменить на</td></tr>';

            for ($i=0;$i<mysqli_num_rows($userres);$i++){
                $user=mysqli_fetch_array($userres,MYSQLI_ASSOC);
                echo '<tr><td>'.$user['UserName'].'</td>';
                $rlink=mysqli_connect( HOST, USER, PASSWORD, DB );
                $uid=$user['Id'];
                $rquery="SELECT RoleId FROM userroles WHERE UserId=$uid";
                $rres=mysqli_query($rlink,$rquery,MYSQLI_STORE_RESULT);
                $role=mysqli_fetch_array($rres,MYSQLI_ASSOC);
                $roleid=$role['RoleId'];
                $rquery="SELECT RoleName FROM roles WHERE Id=$roleid";
                $rlink->set_charset("utf8");
                $rres=mysqli_query($rlink,$rquery,MYSQLI_STORE_RESULT);
                $r=mysqli_fetch_array($rres,MYSQLI_ASSOC);
                echo '<td>'.$r['RoleName'].'</td><td>';
                $rquery="SELECT * FROM roles";
                $rres=mysqli_query($rlink,$rquery,MYSQLI_STORE_RESULT);
                echo '<form method="post" action="?option=roleredresult"><select name="roles">';

                for ($j=0;$j<mysqli_num_rows($rres);$j++){
                    $roleu=mysqli_fetch_array($rres,MYSQLI_ASSOC);
                    echo '<option value="'.$roleu['Id'].'">'.$roleu['RoleName'].'</option>';
                }

                echo '<input value="'.$uid.'" hidden="hidden" name="uid"></select><input type="submit" value="Изменить"></form>';
                echo '</td></tr>';
            }

            echo '</table>';
        }
        else{
            echo 'У вас нет доступа для просмотра этой страницы.';
        }
    }
}