<?php


class sellot extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub

        $rolelink=mysqli_connect( HOST, USER, PASSWORD, DB );
        $userrole=$_SESSION['role'];
        $rolequery="SELECT FlagId FROM rolesflags WHERE RoleId=$userrole AND FlagId=1";
        $roleres=mysqli_query($rolelink,$rolequery,MYSQLI_STORE_RESULT);

        if(mysqli_num_rows($roleres)>0) {
            $uid=$_SESSION['UserId'];
            $cost=trim($_POST['cost']);
            $sum=floor($cost*0.95);
            $lotid=$_POST['lot'];
            $link=mysqli_connect(HOST,USER,PASSWORD,DB);
            $query="UPDATE loot SET Cost=$sum, StatusId=3 WHERE Id=$lotid AND TraderId=$uid";
            $res=mysqli_query($link,$query,MYSQLI_STORE_RESULT);

            if($res==false){
                echo 'Что-то пошло не так';
            }
            else{
                $guildlink=mysqli_connect(HOST,USER,PASSWORD,DB);
                $guildquery="UPDATE wg SET AllSum=AllSum+$cost";
                $guildres=mysqli_query($guildlink,$guildquery,MYSQLI_STORE_RESULT);

                $lotlink=mysqli_connect(HOST,USER,PASSWORD,DB);
                $lotquery="SELECT UserId FROM userloot WHERE LootId=$lotid";
                $lotres=mysqli_query($lotlink,$lotquery,MYSQLI_STORE_RESULT);
                $usermoney=floor($sum/mysqli_num_rows($lotres));

                for ($i=0;$i<mysqli_num_rows($lotres);$i++){
                    $user=mysqli_fetch_array($lotres,MYSQLI_ASSOC);
                    $userid=$user['UserId'];
                    $cashlink=mysqli_connect(HOST,USER,PASSWORD,DB);
                    $cashquery="UPDATE bank SET Sum=Sum+$usermoney WHERE UserId=$userid";
                    $cashres=mysqli_query($cashlink,$cashquery,MYSQLI_STORE_RESULT);
                }

                echo 'Лот успешно закрыт.';
            }
        }
        else{
            echo 'У вас недостаточно прав дл просмотра этой страницы.';
        }
    }
}