<?php


class userexit extends core
{
    public function get_body()
    {
        parent::get_body(); // TODO: Change the autogenerated stub
        $_SESSION = array();
        session_destroy();
        echo 'Вы успешно вышли.';
    }
}